#! /bin/bash

#
# discard all history -- this breaks all forks!
#

if [ -z "$*" ]; then
	echo "git-collapse COMMIT_MESSAGE"
	echo "Collapses all the repository history in the master branch"
	echo
	echo "ATTENTION: git-collapse cannot be undone and breaks forks!"
	exit
fi

# Create a new temporary branch with all the latest revision
# Delete the branch master
# And rename to master the temporary branch 

git checkout --orphan latest_branch \
	&& git add -A \
	&& git commit -am "$*" \
	&& git branch -D master \
	&& git branch -m master \
	&& git push -f origin master

